//TEST GET HTTPREQUEST

GET http://localhost:3000/
Accept: application/json

### GET ALL USERS
GET http://localhost:3000/users/getAllUsers
Accept: application/json

### GET ALL BOOKPLACES
GET http://localhost:3000/bookplaces/getAllBookplaces
Accept: application/json

### GET TEST ROUTES WITH THROW NEW ERROR
GET  http://localhost:3000/test/testRoutes
Content-Type: application/json

{
"number": 1
}

### GET TEST RTE GETALLBOOKPLACEBYUSERID

GET http://localhost:3000/bookplaces/getAllBookPlaceByUserId/daeaa36f-f73c-41be-848d-4bfa266f0a8a
Accept: application/json