GET http://localhost:3000/
Accept: application/json

### GET ALL USERS
GET http://localhost:3000/users/getAllUsers
Accept: application/json

### GET ALL BOOKPLACES
GET http://localhost:3000/bookplaces/getAllBookplaces
Accept: application/json

### GET TEST ROUTES WITH THROW NEW ERROR
GET  http://localhost:3000/test/testRoutes
Content-Type: application/json

{
"number": 1
}

### GET TEST RTE GETALLBOOKPLACEBYUSERID

GET http://localhost:3000/bookplaces/getAllBookPlaceByUserId/cca5e5e8-258a-4e34-9019-1d4d8f40b5d2
Accept: application/json

### GET all comments by bookplace id